# -*- coding: utf-8 -*-
"""SISTEM CERDAS DETEKSI RISIKO KESEHATAN MATA LANSIA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQ9XQRUVkCGmoB3GyTX4W63whWHOhXNh
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# ==========================================
# 1. KONFIGURASI HALAMAN
# ==========================================
st.set_page_config(
    page_title="Deteksi Kesehatan Mata Lansia",
    page_icon="👁️",
    layout="wide"
)

# ==========================================
# 2. FUNGSI LOAD & TRAIN MODEL (CACHED)
# ==========================================
@st.cache_resource
def train_model():
    # Load data
    df = pd.read_csv('patient_data.csv')
    df_lansia = df[df['age'] >= 60].copy()

    # Labeling
    df_lansia['Label_Risiko'] = (df_lansia['has_eye_disease'] | df_lansia['has_diabetic_retinopathy']).astype(int)

    # Cleaning BP
    df_lansia[['systolic', 'diastolic']] = df_lansia['blood_pressure'].str.split('/', expand=True).astype(float)

    features = ['sugar_percentage', 'glucose_percentage', 'cholesterol_percentage',
                'obesity_percentage', 'heart_rate', 'systolic', 'diastolic']
    X = df_lansia[features]
    y = df_lansia['Label_Risiko']

    # Training
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model, features

# Inisialisasi Model
model, feature_names = train_model()

# ==========================================
# 3. INTERFACE STREAMLIT
# ==========================================

st.title("👁️ Sistem Cerdas Deteksi Risiko Kesehatan Mata Lansia")
st.markdown("""
Aplikasi ini menggunakan algoritma **Random Forest** untuk memprediksi risiko penyakit mata
(seperti Retinopati Diabetik) pada lansia usia 60 tahun ke atas berdasarkan parameter klinis.
""")
st.divider()

# Menggunakan Sidebar untuk Input
st.sidebar.header("📥 Input Data Pemeriksaan")

with st.sidebar:
    in_sugar = st.number_input("Sugar Percentage (%)", min_value=0.0, max_value=20.0, value=5.0, step=0.1)
    in_glucose = st.number_input("Glucose Percentage (mg/dL)", min_value=50.0, max_value=300.0, value=90.0)
    in_chol = st.number_input("Cholesterol (mg/dL)", min_value=100.0, max_value=400.0, value=180.0)
    in_obesity = st.number_input("Obesity Percentage (%)", min_value=10.0, max_value=50.0, value=22.0)
    in_hr = st.number_input("Heart Rate (bpm)", min_value=40, max_value=150, value=75)
    in_sys = st.number_input("Sistolik (mmHg)", min_value=80, max_value=200, value=120)
    in_dia = st.number_input("Diastolik (mmHg)", min_value=50, max_value=120, value=80)

    btn_prediksi = st.sidebar.button("Mulai Analisis")

# Bagian Utama (Main Panel)
col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("📋 Data yang Dimasukkan")
    data_user = {
        "Parameter": feature_names,
        "Nilai": [in_sugar, in_glucose, in_chol, in_obesity, in_hr, in_sys, in_dia]
    }
    st.table(pd.DataFrame(data_user))

with col2:
    st.subheader("🎯 Hasil Diagnosa")

    if btn_prediksi:
        # Prediksi
        user_df = pd.DataFrame([[in_sugar, in_glucose, in_chol, in_obesity, in_hr, in_sys, in_dia]],
                               columns=feature_names)

        prob_ml = model.predict_proba(user_df)[0][1]

        # Logika Hybrid (Adjustment)
        unnormal_flags = 0
        if in_sugar > 7.0: unnormal_flags += 1
        if in_glucose > 120: unnormal_flags += 1
        if in_chol > 220: unnormal_flags += 1
        if in_sys > 140: unnormal_flags += 1

        if unnormal_flags == 0 and prob_ml < 0.65:
            final_prob = prob_ml * 0.7
        else:
            final_prob = prob_ml

        # Tampilan Hasil
        st.metric(label="Skor Risiko", value=f"{final_prob*100:.2f}%")

        if final_prob >= 0.5:
            st.error("STATUS: TERDETEKSI RISIKO TINGGI")
            st.warning("**Kesimpulan:** Terdapat pola indikasi penyakit mata/retinopati.")
            st.info("**Rekomendasi:** Segera lakukan pemeriksaan Funduskopi ke Dokter Spesialis Mata.")
        else:
            st.success("STATUS: RISIKO RENDAH (NORMAL)")
            st.write("**Kesimpulan:** Kondisi parameter kesehatan mata dalam batas wajar.")
            st.write("**Rekomendasi:** Tetap jaga pola makan dan cek rutin setiap 12 bulan.")
    else:
        st.info("Klik tombol **'Mulai Analisis'** di sidebar untuk melihat hasil.")

st.divider()
st.caption("Aplikasi ini merupakan alat skrining awal dan bukan pengganti diagnosa medis profesional.")